
name: Python CI on AWS EC2

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests on EC2
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Python version
        run: python3 --version

      - name: Create virtual environment
        run: python3 -m venv .venv

      - name: Install dependencies
        run: .venv/bin/python -m pip install -r requirements.txt

      - name: Run Python tests
        run: .venv/bin/python -m pytest -v